name: Python Application

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      ARM_ENVIRONMENT: ${{ github.variables.ARM_ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          python test.py

     
