name: Python test Application

on:
  push:
    branches:
      - main

jobs:
  print-variable:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: ${{ vars.MY_VARIABLE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: |
          python test.py
